/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthorDto {
  email?: string;
  id?: number;
  name?: string;
  profilePicture?: string;
}
