/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponseDto {
  authenticated?: boolean;
  createdAt?: string;
  email?: string;
  id?: number;
  name?: string;
  profilePicture?: string;
  role?: string;
  bio?: string;
}
