/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthorDto } from '../models/author-dto';
export interface CommentResponse {
  author?: AuthorDto;
  content?: string;
  createdAt?: string;
  id?: number;
  likeCount?: number;
  parentCommentId?: number;
  postId?: number;
  replies?: Array<CommentResponse>;
  replyCount?: number;
  status?: 'ACTIVE' | 'DELETED' | 'HIDDEN';
  updatedAt?: string;
}
