/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDto {
  authorId?: number;
  authorName?: string;
  authorProfilePicture?: string;
  content?: string;
  createdAt?: string;
  id?: number;
  isApproved?: boolean;
  parentCommentId?: number;
  postId?: number;
  postTitle?: string;
  replies?: Array<CommentDto>;
  updatedAt?: string;
}
