/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCommentRequest {
  content?: string;
  createdAt?: string;
  id?: number;
  likeCount?: number;
  parentCommentId?: number;
  postId: number;
  status?: 'ACTIVE' | 'DELETED' | 'HIDDEN';
  updatedAt?: string;
}
