/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePostRequest {
  commentCount?: number;
  content?: string;
  createdAt?: string;
  featuredImage?: string;
  id?: number;
  likeCount?: number;
  likedByCurrentUser?: boolean;
  readTime?: number;
  slug?: string;
  status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' | 'DELETED';
  summary?: string;
  title?: string;
  updatedAt?: string;
  viewCount?: number;
}
