/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LikeDto {
  createdAt?: string;
  id?: number;
  postId?: number;
  postTitle?: string;
  userId?: number;
  userName?: string;
}
