/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OAuthProviderInfoDto {
  lastUsedAt?: string;
  linkedAt?: string;
  providerUserId?: string;
}
