/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { PostDto } from '../models/post-dto';
export interface PagedModelPostDto {
  content?: Array<PostDto>;
  page?: PageMetadata;
}
