/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { UserDto } from '../models/user-dto';
export interface PagedModelUserDto {
  content?: Array<UserDto>;
  page?: PageMetadata;
}
