/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { PostViewDto } from '../models/post-view-dto';
export interface PagedModelPostViewDto {
  content?: Array<PostViewDto>;
  page?: PageMetadata;
}
