/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentDto } from '../models/comment-dto';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelCommentDto {
  content?: Array<CommentDto>;
  page?: PageMetadata;
}
