/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { PostResponse } from '../models/post-response';
export interface PagedModelPostResponse {
  content?: Array<PostResponse>;
  page?: PageMetadata;
}
