/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostViewDto {
  id?: number;
  ipAddress?: string;
  postId?: number;
  postTitle?: string;
  userAgent?: string;
  userId?: number;
  userName?: string;
  viewedAt?: string;
}
