/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileStatsDto {
  commentsDelta?: number;
  likesDelta?: number;
  postsDelta?: number;
  publishedPostsDelta?: number;
  viewsDelta?: number;
}
