/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserRequest {
  bio?: string;
  commentNotifications?: boolean;
  emailNotifications?: boolean;
  enabled?: boolean;
  firstName?: string;
  lastName?: string;
  likeNotifications?: boolean;
  name?: string;
  newsletterSubscribed?: boolean;
  profilePicture?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_USER' | 'ROLE_GUEST';
  showOnlineStatus?: boolean;
}
