/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSettingsDto {
  commentNotifications?: boolean;
  emailNotifications?: boolean;
  likeNotifications?: boolean;
  newsletterSubscribed?: boolean;
  publicProfile?: boolean;
  showOnlineStatus?: boolean;
}
