/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePostDto {
  allowComments?: boolean;
  content?: string;
  featuredImage?: string;
  isFeatured?: boolean;
  postId?: number;
  slug?: string;
  status?: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED' | 'DELETED';
  summary?: string;
  title?: string;
}
