/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OAuthProviderInfoDto } from '../models/o-auth-provider-info-dto';
export interface UserResponse {
  bio?: string;
  commentNotifications?: boolean;
  createdAt?: string;
  email?: string;
  emailNotifications?: boolean;
  enabled?: boolean;
  engagementRate?: number;
  firstName?: string;
  id?: number;
  lastActivityAt?: string;
  lastLoginAt?: string;
  lastName?: string;
  likeNotifications?: boolean;
  linkedProviders?: {
[key: string]: OAuthProviderInfoDto;
};
  name?: string;
  newsletterSubscribed?: boolean;
  profilePicture?: string;
  publicProfile?: boolean;
  publishedPosts?: number;
  role?: 'ROLE_ADMIN' | 'ROLE_USER' | 'ROLE_GUEST';
  showOnlineStatus?: boolean;
  totalCommentsReceived?: number;
  totalLikesReceived?: number;
  totalPosts?: number;
  totalViewsReceived?: number;
  updatedAt?: string;
}
