/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  bio?: string;
  commentNotifications?: boolean;
  company?: string;
  createdAt?: string;
  email?: string;
  emailNotifications?: boolean;
  enabled?: boolean;
  engagementRate?: number;
  githubUsername?: string;
  id?: number;
  jobTitle?: string;
  joinDate?: string;
  lastActivityAt?: string;
  lastLoginAt?: string;
  likeNotifications?: boolean;
  linkedinUrl?: string;
  location?: string;
  name?: string;
  newsletterSubscribed?: boolean;
  profilePicture?: string;
  publicProfile?: boolean;
  publishedPosts?: number;
  role?: string;
  showOnlineStatus?: boolean;
  totalCommentsReceived?: number;
  totalLikesReceived?: number;
  totalPosts?: number;
  totalViewsReceived?: number;
  twitterHandle?: string;
  updatedAt?: string;
  websiteUrl?: string;
}
