/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserStatsResponse {
  activeUsers?: number;
  inactiveUsers?: number;
  totalUsers?: number;
  usersByRole?: {
[key: string]: number;
};
}
