/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponse } from '../../models/comment-response';

export interface GetPostCommentsWithReplies$Params {
  postId: number;
}

export function getPostCommentsWithReplies(http: HttpClient, rootUrl: string, params: GetPostCommentsWithReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getPostCommentsWithReplies.PATH, 'get');
  if (params) {
    rb.path('postId', params.postId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommentResponse>>;
    })
  );
}

getPostCommentsWithReplies.PATH = '/api/v1/comments/post/{postId}/with-replies';
