/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthResponseDto } from '../models/auth-response-dto';
import { generateToken } from '../fn/auth-controller/generate-token';
import { GenerateToken$Params } from '../fn/auth-controller/generate-token';
import { getAuthStatus } from '../fn/auth-controller/get-auth-status';
import { GetAuthStatus$Params } from '../fn/auth-controller/get-auth-status';
import { getCurrentUser } from '../fn/auth-controller/get-current-user';
import { GetCurrentUser$Params } from '../fn/auth-controller/get-current-user';
import { healthCheck } from '../fn/auth-controller/health-check';
import { HealthCheck$Params } from '../fn/auth-controller/health-check';
import { logout } from '../fn/auth-controller/logout';
import { Logout$Params } from '../fn/auth-controller/logout';
import { refreshToken } from '../fn/auth-controller/refresh-token';
import { RefreshToken$Params } from '../fn/auth-controller/refresh-token';
import { validateTokenQuery } from '../fn/auth-controller/validate-token-query';
import { ValidateTokenQuery$Params } from '../fn/auth-controller/validate-token-query';

@Injectable({ providedIn: 'root' })
export class AuthControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `refreshToken()` */
  static readonly RefreshTokenPath = '/auth/refresh-token';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refreshToken()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken$Response(params: RefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return refreshToken(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refreshToken$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  refreshToken(params: RefreshToken$Params, context?: HttpContext): Observable<{
}> {
    return this.refreshToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/auth/logout';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout$Response(params?: Logout$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return logout(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout(params?: Logout$Params, context?: HttpContext): Observable<void> {
    return this.logout$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `validateTokenQuery()` */
  static readonly ValidateTokenQueryPath = '/auth/validate-token';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `validateTokenQuery()` instead.
   *
   * This method doesn't expect any request body.
   */
  validateTokenQuery$Response(params: ValidateTokenQuery$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return validateTokenQuery(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `validateTokenQuery$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  validateTokenQuery(params: ValidateTokenQuery$Params, context?: HttpContext): Observable<{
}> {
    return this.validateTokenQuery$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getCurrentUser()` */
  static readonly GetCurrentUserPath = '/auth/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser$Response(params?: GetCurrentUser$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponseDto>> {
    return getCurrentUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUser(params?: GetCurrentUser$Params, context?: HttpContext): Observable<AuthResponseDto> {
    return this.getCurrentUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthResponseDto>): AuthResponseDto => r.body)
    );
  }

  /** Path part for operation `getAuthStatus()` */
  static readonly GetAuthStatusPath = '/auth/status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAuthStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthStatus$Response(params?: GetAuthStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponseDto>> {
    return getAuthStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAuthStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAuthStatus(params?: GetAuthStatus$Params, context?: HttpContext): Observable<AuthResponseDto> {
    return this.getAuthStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthResponseDto>): AuthResponseDto => r.body)
    );
  }

  /** Path part for operation `healthCheck()` */
  static readonly HealthCheckPath = '/auth/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `healthCheck()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheck$Response(params?: HealthCheck$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return healthCheck(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `healthCheck$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  healthCheck(params?: HealthCheck$Params, context?: HttpContext): Observable<{
}> {
    return this.healthCheck$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `generateToken()` */
  static readonly GenerateTokenPath = '/auth/generate-token';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateToken()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateToken$Response(params?: GenerateToken$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return generateToken(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateToken$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateToken(params?: GenerateToken$Params, context?: HttpContext): Observable<{
}> {
    return this.generateToken$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
