/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { changeCommentStatus } from '../fn/comments/change-comment-status';
import { ChangeCommentStatus$Params } from '../fn/comments/change-comment-status';
import { CommentResponse } from '../models/comment-response';
import { createComment } from '../fn/comments/create-comment';
import { CreateComment$Params } from '../fn/comments/create-comment';
import { decrementLikeCount } from '../fn/comments/decrement-like-count';
import { DecrementLikeCount$Params } from '../fn/comments/decrement-like-count';
import { deleteComment } from '../fn/comments/delete-comment';
import { DeleteComment$Params } from '../fn/comments/delete-comment';
import { getCommentById } from '../fn/comments/get-comment-by-id';
import { GetCommentById$Params } from '../fn/comments/get-comment-by-id';
import { getCommentReplies } from '../fn/comments/get-comment-replies';
import { GetCommentReplies$Params } from '../fn/comments/get-comment-replies';
import { getCommentsByPost } from '../fn/comments/get-comments-by-post';
import { GetCommentsByPost$Params } from '../fn/comments/get-comments-by-post';
import { getCommentsByUser } from '../fn/comments/get-comments-by-user';
import { GetCommentsByUser$Params } from '../fn/comments/get-comments-by-user';
import { getPostCommentCount } from '../fn/comments/get-post-comment-count';
import { GetPostCommentCount$Params } from '../fn/comments/get-post-comment-count';
import { getPostCommentsWithReplies } from '../fn/comments/get-post-comments-with-replies';
import { GetPostCommentsWithReplies$Params } from '../fn/comments/get-post-comments-with-replies';
import { getUserCommentStats } from '../fn/comments/get-user-comment-stats';
import { GetUserCommentStats$Params } from '../fn/comments/get-user-comment-stats';
import { incrementLikeCount } from '../fn/comments/increment-like-count';
import { IncrementLikeCount$Params } from '../fn/comments/increment-like-count';
import { PageCommentResponse } from '../models/page-comment-response';
import { updateComment } from '../fn/comments/update-comment';
import { UpdateComment$Params } from '../fn/comments/update-comment';


/**
 * Comment management APIs
 */
@Injectable({ providedIn: 'root' })
export class CommentsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCommentById()` */
  static readonly GetCommentByIdPath = '/comment/{id}';

  /**
   * Get comment by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCommentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentById$Response(params: GetCommentById$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
    return getCommentById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comment by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCommentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentById(params: GetCommentById$Params, context?: HttpContext): Observable<CommentResponse> {
    return this.getCommentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentResponse>): CommentResponse => r.body)
    );
  }

  /** Path part for operation `updateComment()` */
  static readonly UpdateCommentPath = '/comment/{id}';

  /**
   * Update comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateComment$Response(params: UpdateComment$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
    return updateComment(this.http, this.rootUrl, params, context);
  }

  /**
   * Update comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateComment(params: UpdateComment$Params, context?: HttpContext): Observable<CommentResponse> {
    return this.updateComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentResponse>): CommentResponse => r.body)
    );
  }

  /** Path part for operation `deleteComment()` */
  static readonly DeleteCommentPath = '/comment/{id}';

  /**
   * Delete comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteComment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment$Response(params: DeleteComment$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteComment(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteComment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment(params: DeleteComment$Params, context?: HttpContext): Observable<void> {
    return this.deleteComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `createComment()` */
  static readonly CreateCommentPath = '/comment';

  /**
   * Create a new comment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment$Response(params: CreateComment$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
    return createComment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new comment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment(params: CreateComment$Params, context?: HttpContext): Observable<CommentResponse> {
    return this.createComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentResponse>): CommentResponse => r.body)
    );
  }

  /** Path part for operation `decrementLikeCount()` */
  static readonly DecrementLikeCountPath = '/comment/{id}/unlike';

  /**
   * Decrement comment like count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `decrementLikeCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  decrementLikeCount$Response(params: DecrementLikeCount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return decrementLikeCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Decrement comment like count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `decrementLikeCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  decrementLikeCount(params: DecrementLikeCount$Params, context?: HttpContext): Observable<void> {
    return this.decrementLikeCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `incrementLikeCount()` */
  static readonly IncrementLikeCountPath = '/comment/{id}/like';

  /**
   * Increment comment like count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `incrementLikeCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  incrementLikeCount$Response(params: IncrementLikeCount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return incrementLikeCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Increment comment like count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `incrementLikeCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  incrementLikeCount(params: IncrementLikeCount$Params, context?: HttpContext): Observable<void> {
    return this.incrementLikeCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `changeCommentStatus()` */
  static readonly ChangeCommentStatusPath = '/comment/{id}/status';

  /**
   * Change comment status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeCommentStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeCommentStatus$Response(params: ChangeCommentStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
    return changeCommentStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Change comment status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeCommentStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeCommentStatus(params: ChangeCommentStatus$Params, context?: HttpContext): Observable<CommentResponse> {
    return this.changeCommentStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentResponse>): CommentResponse => r.body)
    );
  }

  /** Path part for operation `getCommentReplies()` */
  static readonly GetCommentRepliesPath = '/comment/{id}/replies';

  /**
   * Get comment replies.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCommentReplies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentReplies$Response(params: GetCommentReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentResponse>>> {
    return getCommentReplies(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comment replies.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCommentReplies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentReplies(params: GetCommentReplies$Params, context?: HttpContext): Observable<Array<CommentResponse>> {
    return this.getCommentReplies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CommentResponse>>): Array<CommentResponse> => r.body)
    );
  }

  /** Path part for operation `getCommentsByUser()` */
  static readonly GetCommentsByUserPath = '/comment/user/{userId}';

  /**
   * Get comments by user (paginated).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCommentsByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsByUser$Response(params: GetCommentsByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<PageCommentResponse>> {
    return getCommentsByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comments by user (paginated).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCommentsByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsByUser(params: GetCommentsByUser$Params, context?: HttpContext): Observable<PageCommentResponse> {
    return this.getCommentsByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageCommentResponse>): PageCommentResponse => r.body)
    );
  }

  /** Path part for operation `getUserCommentStats()` */
  static readonly GetUserCommentStatsPath = '/comment/stats';

  /**
   * Get user comment statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserCommentStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserCommentStats$Response(params?: GetUserCommentStats$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getUserCommentStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user comment statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserCommentStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserCommentStats(params?: GetUserCommentStats$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getUserCommentStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getCommentsByPost()` */
  static readonly GetCommentsByPostPath = '/comment/post/{postId}';

  /**
   * Get comments by post (paginated).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCommentsByPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsByPost$Response(params: GetCommentsByPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PageCommentResponse>> {
    return getCommentsByPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Get comments by post (paginated).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCommentsByPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCommentsByPost(params: GetCommentsByPost$Params, context?: HttpContext): Observable<PageCommentResponse> {
    return this.getCommentsByPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageCommentResponse>): PageCommentResponse => r.body)
    );
  }

  /** Path part for operation `getPostCommentsWithReplies()` */
  static readonly GetPostCommentsWithRepliesPath = '/comment/post/{postId}/with-replies';

  /**
   * Get all comments with replies for a post.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostCommentsWithReplies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostCommentsWithReplies$Response(params: GetPostCommentsWithReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentResponse>>> {
    return getPostCommentsWithReplies(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all comments with replies for a post.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostCommentsWithReplies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostCommentsWithReplies(params: GetPostCommentsWithReplies$Params, context?: HttpContext): Observable<Array<CommentResponse>> {
    return this.getPostCommentsWithReplies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CommentResponse>>): Array<CommentResponse> => r.body)
    );
  }

  /** Path part for operation `getPostCommentCount()` */
  static readonly GetPostCommentCountPath = '/comment/post/{postId}/count';

  /**
   * Get post comment count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostCommentCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostCommentCount$Response(params: GetPostCommentCount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getPostCommentCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post comment count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostCommentCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostCommentCount(params: GetPostCommentCount$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getPostCommentCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

}
