/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CommentDto } from '../models/comment-dto';
import { createComment } from '../fn/comment-controller/create-comment';
import { CreateComment$Params } from '../fn/comment-controller/create-comment';
import { deleteComment } from '../fn/comment-controller/delete-comment';
import { DeleteComment$Params } from '../fn/comment-controller/delete-comment';
import { getMyComments } from '../fn/comment-controller/get-my-comments';
import { GetMyComments$Params } from '../fn/comment-controller/get-my-comments';
import { getPostComments } from '../fn/comment-controller/get-post-comments';
import { GetPostComments$Params } from '../fn/comment-controller/get-post-comments';
import { PagedModelCommentDto } from '../models/paged-model-comment-dto';
import { updateComment } from '../fn/comment-controller/update-comment';
import { UpdateComment$Params } from '../fn/comment-controller/update-comment';

@Injectable({ providedIn: 'root' })
export class CommentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateComment()` */
  static readonly UpdateCommentPath = '/api/posts/{postId}/comments/{commentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateComment()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateComment$Response(params: UpdateComment$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentDto>> {
    return updateComment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateComment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateComment(params: UpdateComment$Params, context?: HttpContext): Observable<CommentDto> {
    return this.updateComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentDto>): CommentDto => r.body)
    );
  }

  /** Path part for operation `deleteComment()` */
  static readonly DeleteCommentPath = '/api/posts/{postId}/comments/{commentId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteComment()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment$Response(params: DeleteComment$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteComment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteComment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteComment(params: DeleteComment$Params, context?: HttpContext): Observable<void> {
    return this.deleteComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getPostComments()` */
  static readonly GetPostCommentsPath = '/api/posts/{postId}/comments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostComments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostComments$Response(params: GetPostComments$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelCommentDto>> {
    return getPostComments(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostComments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostComments(params: GetPostComments$Params, context?: HttpContext): Observable<PagedModelCommentDto> {
    return this.getPostComments$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelCommentDto>): PagedModelCommentDto => r.body)
    );
  }

  /** Path part for operation `createComment()` */
  static readonly CreateCommentPath = '/api/posts/{postId}/comments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createComment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment$Response(params: CreateComment$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentDto>> {
    return createComment(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createComment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createComment(params: CreateComment$Params, context?: HttpContext): Observable<CommentDto> {
    return this.createComment$Response(params, context).pipe(
      map((r: StrictHttpResponse<CommentDto>): CommentDto => r.body)
    );
  }

  /** Path part for operation `getMyComments()` */
  static readonly GetMyCommentsPath = '/api/comments/my-comments';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyComments()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyComments$Response(params?: GetMyComments$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelCommentDto>> {
    return getMyComments(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyComments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyComments(params?: GetMyComments$Params, context?: HttpContext): Observable<PagedModelCommentDto> {
    return this.getMyComments$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelCommentDto>): PagedModelCommentDto => r.body)
    );
  }

}
