/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLikeCount } from '../fn/like-controller/get-like-count';
import { GetLikeCount$Params } from '../fn/like-controller/get-like-count';
import { getUsersWhoLikedPost } from '../fn/like-controller/get-users-who-liked-post';
import { GetUsersWhoLikedPost$Params } from '../fn/like-controller/get-users-who-liked-post';
import { hasLikedPost } from '../fn/like-controller/has-liked-post';
import { HasLikedPost$Params } from '../fn/like-controller/has-liked-post';
import { LikeDto } from '../models/like-dto';
import { likePost } from '../fn/like-controller/like-post';
import { LikePost$Params } from '../fn/like-controller/like-post';
import { unlikePost } from '../fn/like-controller/unlike-post';
import { UnlikePost$Params } from '../fn/like-controller/unlike-post';
import { UserDto } from '../models/user-dto';

@Injectable({ providedIn: 'root' })
export class LikeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `likePost()` */
  static readonly LikePostPath = '/api/posts/{postId}/likes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `likePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  likePost$Response(params: LikePost$Params, context?: HttpContext): Observable<StrictHttpResponse<LikeDto>> {
    return likePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `likePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  likePost(params: LikePost$Params, context?: HttpContext): Observable<LikeDto> {
    return this.likePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<LikeDto>): LikeDto => r.body)
    );
  }

  /** Path part for operation `unlikePost()` */
  static readonly UnlikePostPath = '/api/posts/{postId}/likes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unlikePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlikePost$Response(params: UnlikePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return unlikePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unlikePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlikePost(params: UnlikePost$Params, context?: HttpContext): Observable<void> {
    return this.unlikePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUsersWhoLikedPost()` */
  static readonly GetUsersWhoLikedPostPath = '/api/posts/{postId}/likes/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersWhoLikedPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersWhoLikedPost$Response(params: GetUsersWhoLikedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDto>>> {
    return getUsersWhoLikedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersWhoLikedPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersWhoLikedPost(params: GetUsersWhoLikedPost$Params, context?: HttpContext): Observable<Array<UserDto>> {
    return this.getUsersWhoLikedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserDto>>): Array<UserDto> => r.body)
    );
  }

  /** Path part for operation `hasLikedPost()` */
  static readonly HasLikedPostPath = '/api/posts/{postId}/likes/has-liked';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hasLikedPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasLikedPost$Response(params: HasLikedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return hasLikedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hasLikedPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasLikedPost(params: HasLikedPost$Params, context?: HttpContext): Observable<boolean> {
    return this.hasLikedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getLikeCount()` */
  static readonly GetLikeCountPath = '/api/posts/{postId}/likes/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLikeCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeCount$Response(params: GetLikeCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getLikeCount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLikeCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeCount(params: GetLikeCount$Params, context?: HttpContext): Observable<number> {
    return this.getLikeCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
