/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createPosts } from '../fn/post-controller/create-posts';
import { CreatePosts$Params } from '../fn/post-controller/create-posts';
import { deletePost } from '../fn/post-controller/delete-post';
import { DeletePost$Params } from '../fn/post-controller/delete-post';
import { getFeaturedPosts } from '../fn/post-controller/get-featured-posts';
import { GetFeaturedPosts$Params } from '../fn/post-controller/get-featured-posts';
import { getMyDrafts } from '../fn/post-controller/get-my-drafts';
import { GetMyDrafts$Params } from '../fn/post-controller/get-my-drafts';
import { getMyPosts } from '../fn/post-controller/get-my-posts';
import { GetMyPosts$Params } from '../fn/post-controller/get-my-posts';
import { getPostBySlug } from '../fn/post-controller/get-post-by-slug';
import { GetPostBySlug$Params } from '../fn/post-controller/get-post-by-slug';
import { getPostsByStatus } from '../fn/post-controller/get-posts-by-status';
import { GetPostsByStatus$Params } from '../fn/post-controller/get-posts-by-status';
import { getPublishedPosts } from '../fn/post-controller/get-published-posts';
import { GetPublishedPosts$Params } from '../fn/post-controller/get-published-posts';
import { PagedModelPostDto } from '../models/paged-model-post-dto';
import { PostDto } from '../models/post-dto';
import { publishPost } from '../fn/post-controller/publish-post';
import { PublishPost$Params } from '../fn/post-controller/publish-post';
import { searchPosts } from '../fn/post-controller/search-posts';
import { SearchPosts$Params } from '../fn/post-controller/search-posts';
import { unpublishPost } from '../fn/post-controller/unpublish-post';
import { UnpublishPost$Params } from '../fn/post-controller/unpublish-post';
import { updatePost } from '../fn/post-controller/update-post';
import { UpdatePost$Params } from '../fn/post-controller/update-post';
import { updatePosts } from '../fn/post-controller/update-posts';
import { UpdatePosts$Params } from '../fn/post-controller/update-posts';

@Injectable({ providedIn: 'root' })
export class PostControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `unpublishPost()` */
  static readonly UnpublishPostPath = '/api/posts/{postId}/unpublish';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unpublishPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  unpublishPost$Response(params: UnpublishPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return unpublishPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unpublishPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unpublishPost(params: UnpublishPost$Params, context?: HttpContext): Observable<PostDto> {
    return this.unpublishPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `publishPost()` */
  static readonly PublishPostPath = '/api/posts/{postId}/publish';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `publishPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  publishPost$Response(params: PublishPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return publishPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `publishPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  publishPost(params: PublishPost$Params, context?: HttpContext): Observable<PostDto> {
    return this.publishPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `createPosts()` */
  static readonly CreatePostsPath = '/api/posts/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPosts()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPosts$Response(params: CreatePosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return createPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPosts$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPosts(params: CreatePosts$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.createPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

  /** Path part for operation `deletePost()` */
  static readonly DeletePostPath = '/api/posts/{postId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost$Response(params: DeletePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost(params: DeletePost$Params, context?: HttpContext): Observable<void> {
    return this.deletePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updatePost()` */
  static readonly UpdatePostPath = '/api/posts/{postId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost$Response(params: UpdatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return updatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost(params: UpdatePost$Params, context?: HttpContext): Observable<PostDto> {
    return this.updatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `updatePosts()` */
  static readonly UpdatePostsPath = '/api/posts/bulk';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePosts()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePosts$Response(params: UpdatePosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return updatePosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePosts$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePosts(params: UpdatePosts$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.updatePosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

  /** Path part for operation `getPublishedPosts()` */
  static readonly GetPublishedPostsPath = '/api/posts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublishedPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedPosts$Response(params?: GetPublishedPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostDto>> {
    return getPublishedPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublishedPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedPosts(params?: GetPublishedPosts$Params, context?: HttpContext): Observable<PagedModelPostDto> {
    return this.getPublishedPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostDto>): PagedModelPostDto => r.body)
    );
  }

  /** Path part for operation `getPostBySlug()` */
  static readonly GetPostBySlugPath = '/api/posts/{slug}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostBySlug()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostBySlug$Response(params: GetPostBySlug$Params, context?: HttpContext): Observable<StrictHttpResponse<PostDto>> {
    return getPostBySlug(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostBySlug$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostBySlug(params: GetPostBySlug$Params, context?: HttpContext): Observable<PostDto> {
    return this.getPostBySlug$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostDto>): PostDto => r.body)
    );
  }

  /** Path part for operation `getPostsByStatus()` */
  static readonly GetPostsByStatusPath = '/api/posts/status/{status}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostsByStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsByStatus$Response(params: GetPostsByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostDto>> {
    return getPostsByStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostsByStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostsByStatus(params: GetPostsByStatus$Params, context?: HttpContext): Observable<PagedModelPostDto> {
    return this.getPostsByStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostDto>): PagedModelPostDto => r.body)
    );
  }

  /** Path part for operation `searchPosts()` */
  static readonly SearchPostsPath = '/api/posts/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPosts$Response(params: SearchPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostDto>> {
    return searchPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPosts(params: SearchPosts$Params, context?: HttpContext): Observable<PagedModelPostDto> {
    return this.searchPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostDto>): PagedModelPostDto => r.body)
    );
  }

  /** Path part for operation `getMyPosts()` */
  static readonly GetMyPostsPath = '/api/posts/my-posts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPosts$Response(params?: GetMyPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostDto>>> {
    return getMyPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPosts(params?: GetMyPosts$Params, context?: HttpContext): Observable<Array<PostDto>> {
    return this.getMyPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PostDto>>): Array<PostDto> => r.body)
    );
  }

  /** Path part for operation `getMyDrafts()` */
  static readonly GetMyDraftsPath = '/api/posts/my-drafts';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyDrafts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyDrafts$Response(params?: GetMyDrafts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostDto>> {
    return getMyDrafts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyDrafts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyDrafts(params?: GetMyDrafts$Params, context?: HttpContext): Observable<PagedModelPostDto> {
    return this.getMyDrafts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostDto>): PagedModelPostDto => r.body)
    );
  }

  /** Path part for operation `getFeaturedPosts()` */
  static readonly GetFeaturedPostsPath = '/api/posts/featured';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeaturedPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeaturedPosts$Response(params?: GetFeaturedPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostDto>> {
    return getFeaturedPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeaturedPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeaturedPosts(params?: GetFeaturedPosts$Params, context?: HttpContext): Observable<PagedModelPostDto> {
    return this.getFeaturedPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostDto>): PagedModelPostDto => r.body)
    );
  }

}
