/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getPostViews } from '../fn/post-view-controller/get-post-views';
import { GetPostViews$Params } from '../fn/post-view-controller/get-post-views';
import { getViewCount } from '../fn/post-view-controller/get-view-count';
import { GetViewCount$Params } from '../fn/post-view-controller/get-view-count';
import { hasViewedPost } from '../fn/post-view-controller/has-viewed-post';
import { HasViewedPost$Params } from '../fn/post-view-controller/has-viewed-post';
import { PagedModelPostViewDto } from '../models/paged-model-post-view-dto';
import { PostViewDto } from '../models/post-view-dto';
import { trackView } from '../fn/post-view-controller/track-view';
import { TrackView$Params } from '../fn/post-view-controller/track-view';

@Injectable({ providedIn: 'root' })
export class PostViewControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPostViews()` */
  static readonly GetPostViewsPath = '/api/posts/{postId}/views';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostViews()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostViews$Response(params: GetPostViews$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostViewDto>> {
    return getPostViews(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostViews$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostViews(params: GetPostViews$Params, context?: HttpContext): Observable<PagedModelPostViewDto> {
    return this.getPostViews$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostViewDto>): PagedModelPostViewDto => r.body)
    );
  }

  /** Path part for operation `trackView()` */
  static readonly TrackViewPath = '/api/posts/{postId}/views';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `trackView()` instead.
   *
   * This method doesn't expect any request body.
   */
  trackView$Response(params: TrackView$Params, context?: HttpContext): Observable<StrictHttpResponse<PostViewDto>> {
    return trackView(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `trackView$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  trackView(params: TrackView$Params, context?: HttpContext): Observable<PostViewDto> {
    return this.trackView$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostViewDto>): PostViewDto => r.body)
    );
  }

  /** Path part for operation `hasViewedPost()` */
  static readonly HasViewedPostPath = '/api/posts/{postId}/views/has-viewed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `hasViewedPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasViewedPost$Response(params: HasViewedPost$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return hasViewedPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `hasViewedPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  hasViewedPost(params: HasViewedPost$Params, context?: HttpContext): Observable<boolean> {
    return this.hasViewedPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getViewCount()` */
  static readonly GetViewCountPath = '/api/posts/{postId}/views/count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getViewCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getViewCount$Response(params: GetViewCount$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return getViewCount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getViewCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getViewCount(params: GetViewCount$Params, context?: HttpContext): Observable<number> {
    return this.getViewCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
