/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { changePostStatus } from '../fn/posts/change-post-status';
import { ChangePostStatus$Params } from '../fn/posts/change-post-status';
import { createPost } from '../fn/posts/create-post';
import { CreatePost$Params } from '../fn/posts/create-post';
import { deletePost } from '../fn/posts/delete-post';
import { DeletePost$Params } from '../fn/posts/delete-post';
import { getAllPosts } from '../fn/posts/get-all-posts';
import { GetAllPosts$Params } from '../fn/posts/get-all-posts';
import { getLikeCount } from '../fn/posts/get-like-count';
import { GetLikeCount$Params } from '../fn/posts/get-like-count';
import { getLikeStatus } from '../fn/posts/get-like-status';
import { GetLikeStatus$Params } from '../fn/posts/get-like-status';
import { getMyPosts } from '../fn/posts/get-my-posts';
import { GetMyPosts$Params } from '../fn/posts/get-my-posts';
import { getPostById } from '../fn/posts/get-post-by-id';
import { GetPostById$Params } from '../fn/posts/get-post-by-id';
import { getPostBySlug } from '../fn/posts/get-post-by-slug';
import { GetPostBySlug$Params } from '../fn/posts/get-post-by-slug';
import { getPublishedPosts } from '../fn/posts/get-published-posts';
import { GetPublishedPosts$Params } from '../fn/posts/get-published-posts';
import { getUserPostStats } from '../fn/posts/get-user-post-stats';
import { GetUserPostStats$Params } from '../fn/posts/get-user-post-stats';
import { getViewCount } from '../fn/posts/get-view-count';
import { GetViewCount$Params } from '../fn/posts/get-view-count';
import { incrementViewCount } from '../fn/posts/increment-view-count';
import { IncrementViewCount$Params } from '../fn/posts/increment-view-count';
import { PagedModelPostResponse } from '../models/paged-model-post-response';
import { PostResponse } from '../models/post-response';
import { searchPosts } from '../fn/posts/search-posts';
import { SearchPosts$Params } from '../fn/posts/search-posts';
import { toggleLike } from '../fn/posts/toggle-like';
import { ToggleLike$Params } from '../fn/posts/toggle-like';
import { updatePost } from '../fn/posts/update-post';
import { UpdatePost$Params } from '../fn/posts/update-post';


/**
 * Post management APIs
 */
@Injectable({ providedIn: 'root' })
export class PostService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getPostById()` */
  static readonly GetPostByIdPath = '/api/v1/posts/{id}';

  /**
   * Get post by ID (only published).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostById$Response(params: GetPostById$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return getPostById(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post by ID (only published).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostById(params: GetPostById$Params, context?: HttpContext): Observable<PostResponse> {
    return this.getPostById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `updatePost()` */
  static readonly UpdatePostPath = '/api/v1/posts/{id}';

  /**
   * Update post.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updatePost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost$Response(params: UpdatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return updatePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Update post.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updatePost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updatePost(params: UpdatePost$Params, context?: HttpContext): Observable<PostResponse> {
    return this.updatePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `deletePost()` */
  static readonly DeletePostPath = '/api/v1/posts/{id}';

  /**
   * Delete post.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deletePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost$Response(params: DeletePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deletePost(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete post.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deletePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deletePost(params: DeletePost$Params, context?: HttpContext): Observable<void> {
    return this.deletePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllPosts()` */
  static readonly GetAllPostsPath = '/api/v1/posts';

  /**
   * Get all posts (paginated).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts$Response(params?: GetAllPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostResponse>> {
    return getAllPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all posts (paginated).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPosts(params?: GetAllPosts$Params, context?: HttpContext): Observable<PagedModelPostResponse> {
    return this.getAllPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostResponse>): PagedModelPostResponse => r.body)
    );
  }

  /** Path part for operation `createPost()` */
  static readonly CreatePostPath = '/api/v1/posts';

  /**
   * Create a new post.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPost$Response(params: CreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return createPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Create a new post.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createPost(params: CreatePost$Params, context?: HttpContext): Observable<PostResponse> {
    return this.createPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `toggleLike()` */
  static readonly ToggleLikePath = '/api/v1/posts/{id}/like';

  /**
   * Toggle like on post.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `toggleLike()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleLike$Response(params: ToggleLike$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return toggleLike(this.http, this.rootUrl, params, context);
  }

  /**
   * Toggle like on post.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `toggleLike$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleLike(params: ToggleLike$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.toggleLike$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

  /** Path part for operation `incrementViewCount()` */
  static readonly IncrementViewCountPath = '/api/v1/posts/{id}/increment-view';

  /**
   * Manually increment view count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `incrementViewCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  incrementViewCount$Response(params: IncrementViewCount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return incrementViewCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Manually increment view count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `incrementViewCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  incrementViewCount(params: IncrementViewCount$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.incrementViewCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `changePostStatus()` */
  static readonly ChangePostStatusPath = '/api/v1/posts/{id}/status';

  /**
   * Change post status.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changePostStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  changePostStatus$Response(params: ChangePostStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return changePostStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Change post status.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changePostStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changePostStatus(params: ChangePostStatus$Params, context?: HttpContext): Observable<PostResponse> {
    return this.changePostStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `getViewCount()` */
  static readonly GetViewCountPath = '/api/v1/posts/{id}/view-count';

  /**
   * Get post view count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getViewCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getViewCount$Response(params: GetViewCount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getViewCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post view count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getViewCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getViewCount(params: GetViewCount$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getViewCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getLikeStatus()` */
  static readonly GetLikeStatusPath = '/api/v1/posts/{id}/like-status';

  /**
   * Get post like status for current user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLikeStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeStatus$Response(params: GetLikeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return getLikeStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post like status for current user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLikeStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeStatus(params: GetLikeStatus$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.getLikeStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

  /** Path part for operation `getLikeCount()` */
  static readonly GetLikeCountPath = '/api/v1/posts/{id}/like-count';

  /**
   * Get post like count.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLikeCount()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeCount$Response(params: GetLikeCount$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getLikeCount(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post like count.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLikeCount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLikeCount(params: GetLikeCount$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getLikeCount$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getUserPostStats()` */
  static readonly GetUserPostStatsPath = '/api/v1/posts/stats';

  /**
   * Get user post statistics.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserPostStats()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPostStats$Response(params?: GetUserPostStats$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getUserPostStats(this.http, this.rootUrl, params, context);
  }

  /**
   * Get user post statistics.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserPostStats$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPostStats(params?: GetUserPostStats$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getUserPostStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getPostBySlug()` */
  static readonly GetPostBySlugPath = '/api/v1/posts/slug/{slug}';

  /**
   * Get post by slug.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPostBySlug()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostBySlug$Response(params: GetPostBySlug$Params, context?: HttpContext): Observable<StrictHttpResponse<PostResponse>> {
    return getPostBySlug(this.http, this.rootUrl, params, context);
  }

  /**
   * Get post by slug.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPostBySlug$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPostBySlug(params: GetPostBySlug$Params, context?: HttpContext): Observable<PostResponse> {
    return this.getPostBySlug$Response(params, context).pipe(
      map((r: StrictHttpResponse<PostResponse>): PostResponse => r.body)
    );
  }

  /** Path part for operation `searchPosts()` */
  static readonly SearchPostsPath = '/api/v1/posts/search';

  /**
   * Search published posts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPosts$Response(params: SearchPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostResponse>> {
    return searchPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * Search published posts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchPosts(params: SearchPosts$Params, context?: HttpContext): Observable<PagedModelPostResponse> {
    return this.searchPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostResponse>): PagedModelPostResponse => r.body)
    );
  }

  /** Path part for operation `getPublishedPosts()` */
  static readonly GetPublishedPostsPath = '/api/v1/posts/published';

  /**
   * Get published posts (paginated).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublishedPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedPosts$Response(params?: GetPublishedPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostResponse>> {
    return getPublishedPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get published posts (paginated).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublishedPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublishedPosts(params?: GetPublishedPosts$Params, context?: HttpContext): Observable<PagedModelPostResponse> {
    return this.getPublishedPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostResponse>): PagedModelPostResponse => r.body)
    );
  }

  /** Path part for operation `getMyPosts()` */
  static readonly GetMyPostsPath = '/api/v1/posts/my-posts';

  /**
   * Get current user's posts.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyPosts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPosts$Response(params?: GetMyPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPostResponse>> {
    return getMyPosts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user's posts.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyPosts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyPosts(params?: GetMyPosts$Params, context?: HttpContext): Observable<PagedModelPostResponse> {
    return this.getMyPosts$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelPostResponse>): PagedModelPostResponse => r.body)
    );
  }

}
