/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { unlinkProvider } from '../fn/user-provider-controller/unlink-provider';
import { UnlinkProvider$Params } from '../fn/user-provider-controller/unlink-provider';

@Injectable({ providedIn: 'root' })
export class UserProviderControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `unlinkProvider()` */
  static readonly UnlinkProviderPath = '/user/providers/{provider}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unlinkProvider()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlinkProvider$Response(params: UnlinkProvider$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return unlinkProvider(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unlinkProvider$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unlinkProvider(params: UnlinkProvider$Params, context?: HttpContext): Observable<{
}> {
    return this.unlinkProvider$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
