/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getMyProfile } from '../fn/user-controller/get-my-profile';
import { GetMyProfile$Params } from '../fn/user-controller/get-my-profile';
import { getTopWriters } from '../fn/user-controller/get-top-writers';
import { GetTopWriters$Params } from '../fn/user-controller/get-top-writers';
import { getUpdatedStats } from '../fn/user-controller/get-updated-stats';
import { GetUpdatedStats$Params } from '../fn/user-controller/get-updated-stats';
import { PagedModelUserDto } from '../models/paged-model-user-dto';
import { searchUsers } from '../fn/user-controller/search-users';
import { SearchUsers$Params } from '../fn/user-controller/search-users';
import { updateMyProfile } from '../fn/user-controller/update-my-profile';
import { UpdateMyProfile$Params } from '../fn/user-controller/update-my-profile';
import { updateMySettings } from '../fn/user-controller/update-my-settings';
import { UpdateMySettings$Params } from '../fn/user-controller/update-my-settings';
import { UserDto } from '../models/user-dto';

@Injectable({ providedIn: 'root' })
export class UserControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateMySettings()` */
  static readonly UpdateMySettingsPath = '/api/users/settings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMySettings()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMySettings$Response(params: UpdateMySettings$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return updateMySettings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMySettings$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMySettings(params: UpdateMySettings$Params, context?: HttpContext): Observable<UserDto> {
    return this.updateMySettings$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `updateMyProfile()` */
  static readonly UpdateMyProfilePath = '/api/users/profile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateMyProfile()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyProfile$Response(params: UpdateMyProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return updateMyProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateMyProfile$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateMyProfile(params: UpdateMyProfile$Params, context?: HttpContext): Observable<UserDto> {
    return this.updateMyProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `getUpdatedStats()` */
  static readonly GetUpdatedStatsPath = '/api/users/update-user-stats';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUpdatedStats()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getUpdatedStats$Response(params: GetUpdatedStats$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return getUpdatedStats(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUpdatedStats$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  getUpdatedStats(params: GetUpdatedStats$Params, context?: HttpContext): Observable<UserDto> {
    return this.getUpdatedStats$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `getTopWriters()` */
  static readonly GetTopWritersPath = '/api/users/top-writers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTopWriters()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTopWriters$Response(params?: GetTopWriters$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelUserDto>> {
    return getTopWriters(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTopWriters$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTopWriters(params?: GetTopWriters$Params, context?: HttpContext): Observable<PagedModelUserDto> {
    return this.getTopWriters$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelUserDto>): PagedModelUserDto => r.body)
    );
  }

  /** Path part for operation `searchUsers()` */
  static readonly SearchUsersPath = '/api/users/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUsers$Response(params: SearchUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelUserDto>> {
    return searchUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchUsers(params: SearchUsers$Params, context?: HttpContext): Observable<PagedModelUserDto> {
    return this.searchUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PagedModelUserDto>): PagedModelUserDto => r.body)
    );
  }

  /** Path part for operation `getMyProfile()` */
  static readonly GetMyProfilePath = '/api/users/my-profile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyProfile()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyProfile$Response(params?: GetMyProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return getMyProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyProfile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyProfile(params?: GetMyProfile$Params, context?: HttpContext): Observable<UserDto> {
    return this.getMyProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

}
