/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthorDto } from './models/author-dto';
export type { CommentResponse } from './models/comment-response';
export type { CreateCommentRequest } from './models/create-comment-request';
export type { CreatePostRequest } from './models/create-post-request';
export type { LoginRequest } from './models/login-request';
export type { OAuthProviderInfoDto } from './models/o-auth-provider-info-dto';
export type { PagedModelCommentResponse } from './models/paged-model-comment-response';
export type { PagedModelPostResponse } from './models/paged-model-post-response';
export type { PageMetadata } from './models/page-metadata';
export type { PostResponse } from './models/post-response';
export type { RegisterRequest } from './models/register-request';
export type { TokenProvider } from './models/token-provider';
export type { UpdateCommentRequest } from './models/update-comment-request';
export type { UpdatePostRequest } from './models/update-post-request';
export type { UpdateUserRequest } from './models/update-user-request';
export type { UserResponse } from './models/user-response';
export type { UserStatsResponse } from './models/user-stats-response';
